version: "3.1"
nlu:
- intent: query_kegiatan
  examples: |
    - [kegiatan](object_type) jam [09.00](jam)
- intent: query_ulang_tahun
  examples: |
    - [ulang tahun]{"entity": "object_type", "value": "personal"} tanggal [01-01-1990](tanggal_lahir)
- intent: command_stop
  examples: |
    - stop memainkan musik
    - matikan musik
- intent: query_lagu_kesukaan
  examples: |
    - apa [lagu kesukaan]{"entity": "object_type", "value": "personal"} [budi](nama_orang)
    - [lagu kesukaan]{"entity": "object_type", "value": "personal"} [budi](nama_orang)
    - sebutkan [lagu kesukaan]{"entity": "object_type", "value": "personal"} [budi](nama_orang)
- intent: greet
  examples: |
    - hai
    - halo sekar
    - halo rasa
    - halo
- intent: bot_challenge
  examples: |
    - apakah kamu robot?
    - saya ingin bertanya apakah kamu robot?
    - saya ingin bertanya apakah kamu manusia?
    - siapa kamu
- intent: affirm
  examples: |
    - ya ganti
    - ganti topik
    - iya ingin tanya yang lain
    - iya
    - yes
- intent: deny
  examples: |
    - sampai nanti
    - terimakasih
    - sudah
    - sampai jumpa
    - selamat tinggal
    - cukup
    - tidak
- intent: query_solat
  examples: |
    - saya ingin bertanya tentang [solat](object_type)
    - [kapan]{"entity": "attribute", "value": "jadwal"} melakukan [solat maghrib](solat)
    - mau tanya tentang [solat](object_type)
    - [jam](attribute) berapa solat [itu](mention)
    - apa saja [solat](object_type) [wajib](jenis) yang harus dilakukan
    - solat [itu](mention) [untuk]{"entity": "attribute", "value": "tujuan"} apa si
    - [jam](attribute) berapa [solat zuhur](solat)
    - [solat](object_type) [sunnah](jenis) apa aja
    - [solat ashar](solat) [buat]{"entity": "attribute", "value": "tujuan"} apa si
- intent: query_penyakit
  examples: |
    - saya sedang [sakit]{"entity": "object_type", "value": "penyakit"}
    - [penyebabnya]{"entity": "attribute", "value": "penyebab"} [diabetes](penyakit) apa
    - penyakit [diabetes](penyakit) [gejalanya]{"entity": "attribute", "value": "gejala"} apa
    - [penyebab](attribute) penyakit [diabetes](penyakit) apa
    - saya ingin bertanya seputar [penyakit](object_type)
    - [tanda]{"entity": "attribute", "value": "gejala"} penyakit [diabetes](penyakit) apa
    - [penyakit](object_type) apa saja yang biasa di derita oleh penghuni panti?
    - [kenapa]{"entity": "attribute", "value": "penyebab"} bisa sakit [diabetes](penyakit) apa
- intent: query_lagu_lagu
  examples: |
    - [mainkan]{"entity": "attribute", "value": "url"} [metallica one](lagu_lagu)
    - [mainkan]{"entity": "attribute", "value": "url"} lagu [frank sinatra new york, new york](lagu_lagu)
    - [lagu]{"entity": "object_type", "value": "lagu_lagu"} apa aja yang kamu tahu?
    - [mainkan]{"entity": "attribute", "value": "url"} lagu [bon jovi wanted dead or alive](lagu_lagu)
    - [mainkan]{"entity": "attribute", "value": "url"} lagu [metallica enter sandman](lagu_lagu)
    - [lagu]{"entity": "object_type", "value": "lagu_lagu"} apa aja yang kamu ketahui?
    - [mainkan]{"entity": "attribute", "value": "url"} lagu [bon jovi you give love a bad name](lagu_lagu)
    - [mainkan]{"entity": "attribute", "value": "url"} lagu [westlife i have a dream](lagu_lagu)
    - [mainkan]{"entity": "attribute", "value": "url"} lagu [the beatles come together](lagu_lagu)
- intent: query_obat
  examples: |
    - [aturan minum]{"entity": "attribute", "value": "dosis"} [nya](mention) gimana
    - [obat](object_type) apa aja yang ada di panti?
    - apa saja yang [tidak boleh]{"entity": "attribute", "value": "larangan"} dikonsumsi saat minum obat [itu](mention)
    - mau tanya tentang [obat-obatan]{"entity": "object_type", "value": "obat"}
    - obat [ini](mention) diminum [waktu]{"entity": "attribute", "value": "jadwal"} apa saja
    - [aturan minum]{"entity": "attribute", "value": "dosis"} [aspirin](obat) gimana
    - mau tanya tentang [obat obatan]{"entity": "object_type", "value": "obat"}
    - obat [metformin](obat) diminum [waktu]{"entity": "attribute", "value": "jadwal"} apa saja
    - disini tersedia [obat](object_type) apa aja?
    - saya mau bertanya tentang [obat-obatan]{"entity": "object_type", "value": "obat"}
    - [obat](object_type) apa yang cocok untuk penyakit [diabetes]{"entity": "attribute", "value": "penyakit"}
- intent: query_pengajian
  examples: |
    - [tadarusan](pengajian) [kapan]{"entity": "attribute", "value": "jadwal"} ya
    - siapa [ustazah]{"entity": "attribute", "value": "pembicara"} saat pengajian [tadarusan](pengajian)?
    - saya ingin bertanya tentang [pengajian](object_type)
    - dimana [tempat](attribute) pengajian [tadarusan](pengajian)?
    - pengajian [tadi](mention) sebenarnya [buat]{"entity": "attribute", "value": "tujuan"} apa?
    - [tadarusan](pengajian) suruh [bawa]{"entity": "attribute", "value": "perlengkapan"} apa ya?
    - [tafsir alquran](pengajian) [hari]{"entity": "attribute", "value": "jadwal"} apa
    - pengajian [tadi](mention) kita [belajar]{"entity": "attribute", "value": "materi"} apa?
    - pengajian [fikih](pengajian) [hari]{"entity": "attribute", "value": "jadwal"} apa
    - kalau hari [senin](jadwal) [pengajian](object_type) apa ya
    - apa saja yang harus [dibawa]{"entity": "attribute", "value": "perlengkapan"} saat [tadarusan](pengajian)?
    - mau nanya tentang [pengajian](object_type)
    - pengajian [fikih](pengajian) sebenarnya [untuk]{"entity": "attribute", "value": "tujuan"} apa?
- synonym: jadwal
  examples: |
    - hari
    - kapan
    - waktu
- synonym: materi
  examples: |
    - belajar
- synonym: tujuan
  examples: |
    - untuk
    - buat
- synonym: perlengkapan
  examples: |
    - bawa
    - dibawa
- synonym: pembicara
  examples: |
    - imam
    - ustad
    - ustazah
- synonym: penyakit
  examples: |
    - sakit
    - diabetes
- synonym: obat
  examples: |
    - obatnya
    - obat obatan
    - obat-obatan
- synonym: penyebab
  examples: |
    - penyebabnya
    - kenapa
- synonym: gejala
  examples: |
    - gejalanya
    - tanda
- synonym: larangan
  examples: |
    - tidak boleh
- synonym: dosis
  examples: |
    - aturan minum
- synonym: personal
  examples: |
    - lagu kesukaan
    - ulang tahun
- synonym: lagu_lagu
  examples: |
    - lagu
- synonym: url
  examples: |
    - mainkan
    - putar
- lookup: pengajian
  examples: |
    - tadarusan
    - tafsir alquran
    - tafsir hadist
    - fikih
    - sejarah islam
- lookup: jadwal
  examples: |
    - senin
    - selasa
    - rabu
    - kamis
    - jumat
    - sabtu
    - minggu
- lookup: solat
  examples: |
    - solat subuh
    - solat zuhur
    - solat ashar
    - solat maghrib
    - solat isya
    - solat dhuha
    - solat tahajud
    - solat istikharah
    - solat hajat
- lookup: jam
  examples: |
    - 04.30
    - 07.00
    - 07.15
    - 08.00
    - 09.00
    - 12.00
    - 12.30
    - 12.45
    - 15.00
    - 18.00
    - 19.00
    - 19.30
    - 19.45
    - 21.00
- lookup: penyakit
  examples: |
    - diabetes
    - tekanan darah tinggi
    - kolesterol tinggi
    - masalah kesehatan jantung
    - masalah kesehatan tulang dan sendi
    - masalah kesehatan mental
    - masalah tidur
- lookup: obat
  examples: |
    - metformin
    - glimepiride
    - lisinopril
    - amlopidine
    - astrovatatin
    - aspirin
    - clopidogrel
    - paracetamol
    - ibuprofen
    - sentraline
    - olanzapine
    - zolpidem
    - doxepin
- lookup: nama_orang
  examples: |
    - budi
    - andi
    - susi
    - sari
    - siti
- lookup: lagu_lagu
  examples: |
    - metallica enter sandman
    - metallica one
    - metallica master of puppets
    - metallica the unforgiven
    - metallica nothing else matters
    - metallica flying without wings
    - bon jovi always
    - bon jovi you give love a bad name
    - frank sinatra fly me to the moon
    - frank sinatra new york, new york
    - frank sinatra my way
    - frank sinatra strangers in the night
